
services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=MySecretPassword
      - POSTGRES_DB=bnpl_db
    container_name: bnpl_dbDB
    volumes:
      - ./postgres:/var/lib/postgresql/data

  app:
    build:
      context: .                    
    image: credit-api-app:latest    
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bnpl_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=MySecretPassword
    container_name: credit_api_app
